/*
 * API Géo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.aero.models;


import javax.persistence.*;
import java.util.Objects;

import java.util.List;

/**
 * Commune
 */
@Entity
@Table(name = "commune")
public class Commune {

  @Id()
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id")
  private Integer id;

  @Column(name = "code")
  private String code = null;

  @Column(name = "nom")
  private String nom = null;


  @Column(name = "code_departement")
  private String codeDepartement = null;

  @Column(name = "code_region")
  private String codeRegion = null;

  @ManyToOne(cascade = {CascadeType.ALL})
  @JoinColumn
  private Departement departement = null;

  @ManyToOne(cascade = {CascadeType.ALL})
  @JoinColumn
  private Region region = null;

  @Column(name = "population")
  private Integer population = null;

  @Column(name = "surface")
  private Float surface = null;


  public Commune code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code INSEE de la commune
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Commune nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom de la commune
   * @return nom
  **/
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }




  public Commune codeDepartement(String codeDepartement) {
    this.codeDepartement = codeDepartement;
    return this;
  }

   /**
   * Code du département associé à la commune
   * @return codeDepartement
  **/
  public String getCodeDepartement() {
    return codeDepartement;
  }

  public void setCodeDepartement(String codeDepartement) {
    this.codeDepartement = codeDepartement;
  }

  public Commune codeRegion(String codeRegion) {
    this.codeRegion = codeRegion;
    return this;
  }

   /**
   * Code de la région associée à la commune
   * @return codeRegion
  **/
  public String getCodeRegion() {
    return codeRegion;
  }

  public void setCodeRegion(String codeRegion) {
    this.codeRegion = codeRegion;
  }

  public Commune departement(Departement departement) {
    this.departement = departement;
    return this;
  }

   /**
   * Get departement
   * @return departement
  **/
  public Departement getDepartement() {
    return departement;
  }

  public void setDepartement(Departement departement) {
    this.departement = departement;
  }

  public Commune region(Region region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  public Region getRegion() {
    return region;
  }

  public void setRegion(Region region) {
    this.region = region;
  }

  public Commune population(Integer population) {
    this.population = population;
    return this;
  }

   /**
   * Population municipale
   * @return population
  **/
  public Integer getPopulation() {
    return population;
  }

  public void setPopulation(Integer population) {
    this.population = population;
  }

  public Commune surface(Float surface) {
    this.surface = surface;
    return this;
  }

   /**
   * Surface de la commune, en mètres-carrés
   * @return surface
  **/
  public Float getSurface() {
    return surface;
  }

  public void setSurface(Float surface) {
    this.surface = surface;
  }







  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Commune commune = (Commune) o;
    return Objects.equals(this.code, commune.code) &&
        Objects.equals(this.nom, commune.nom) &&
        Objects.equals(this.codeDepartement, commune.codeDepartement) &&
        Objects.equals(this.codeRegion, commune.codeRegion) &&
        Objects.equals(this.departement, commune.departement) &&
        Objects.equals(this.region, commune.region) &&
        Objects.equals(this.population, commune.population) &&
        Objects.equals(this.surface, commune.surface);

  }

  @Override
  public int hashCode() {
    return Objects.hash(code, nom, codeDepartement, codeRegion, departement, region, population, surface);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Commune {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    codeDepartement: ").append(toIndentedString(codeDepartement)).append("\n");
    sb.append("    codeRegion: ").append(toIndentedString(codeRegion)).append("\n");
    sb.append("    departement: ").append(toIndentedString(departement)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    population: ").append(toIndentedString(population)).append("\n");
    sb.append("    surface: ").append(toIndentedString(surface)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

