/*
 * API Géo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aero.models;

import javax.persistence.*;
import java.util.Objects;

/**
 * Departement
 */
@Entity
@Table(name = "departement")
public class Departement {

  @Id()
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id")
  private Integer id;

  @Column(name = "code")
  private String code = null;

  @Column(name = "nom")
  private String nom = null;

  @Column(name = "code_region")
  private String codeRegion = null;

  @ManyToOne(cascade = {CascadeType.ALL})
  @JoinColumn
  private Region region = null;

  public Departement code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code du département
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Departement nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom du département
   * @return nom
  **/
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public Departement codeRegion(String codeRegion) {
    this.codeRegion = codeRegion;
    return this;
  }

   /**
   * Code de la région
   * @return codeRegion
  **/
  public String getCodeRegion() {
    return codeRegion;
  }

  public void setCodeRegion(String codeRegion) {
    this.codeRegion = codeRegion;
  }

  public Departement region(Region region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  public Region getRegion() {
    return region;
  }

  public void setRegion(Region region) {
    this.region = region;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Departement departement = (Departement) o;
    return Objects.equals(this.code, departement.code) &&
        Objects.equals(this.nom, departement.nom) &&
        Objects.equals(this.codeRegion, departement.codeRegion) &&
        Objects.equals(this.region, departement.region);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, nom, codeRegion, region);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Departement {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    codeRegion: ").append(toIndentedString(codeRegion)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

